Configure Git identity (#105)
* Declanșează manual workflow
  - trebuie făcut merge pentru că altfel nu se poate testa
---------

Co-authored-by: mcmarius <23401453+mcmarius@users.noreply.github.com>

diff --git a/.github/workflows/rebase-branches.yml b/.github/workflows/rebase-branches.yml
--- a/.github/workflows/rebase-branches.yml
+++ b/.github/workflows/rebase-branches.yml
@@ -27,6 +27,11 @@ jobs:
         uses: actions/checkout@v5
         with:
           fetch-depth: 0
+
+      - name: Configure identity
+        run: |
+          git config user.email "${{ github.actor }}@users.noreply.github.com"
+          git config user.name "${{ github.actor }}"
       
       - name: Fetch branches
         run: |
@@ -71,11 +76,24 @@ jobs:
             git checkout -B "$BRANCH" "origin/$BRANCH"
             
             if git rebase "origin/$BASE"; then
-              git push origin "$BRANCH" --force-with-lease
-              echo "Rebased $BRANCH"
+              echo "Rebase succeeded"
+              # FIXME
+              # (git push origin "$BRANCH" --force-with-lease && echo "Rebased $BRANCH") || echo "Push failed"
             else
               echo "Conflict on $BRANCH"
               git rebase --abort
             fi
             echo "-----------------------------------"
           done <<< "$(cat branches.txt)"
+
+      # https://github.com/orgs/community/discussions/25702
+      # - name: Trigger Publish Workflow
+      #   # renovate: datasource=github-tags depName=actions/github-script versioning=loose
+      #   uses: actions/github-script@v7
+      #   with:
+      #     script: |
+      #       github.rest.repos.createDispatchEvent({
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         event_type: 'publish-trigger',
+      #       });
